#!/usr/bin/env python3
import signal
import sys
import subprocess
import venv
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR = _PROGRAM_DIR / ".venv"

# ignore SIGINT in this process, let the subprocess handle it and return
signal.signal(signal.SIGINT, signal.SIG_IGN)

context = venv.EnvBuilder().ensure_directories(_VENV_DIR)
subprocess.check_call([context.env_exe, "-m", "wyoming_whisper_cpp"] + sys.argv[1:])
